"""Toshkentdagi haqiqiy kutubxonalar (OpenStreetMap koordinatalari asosida)."""

REAL_LIBRARIES = [
    {
        "name": "O'zbekiston Milliy kutubxonasi",
        "description": "Alisher Navoiy nomidagi O'zbekiston Milliy kutubxonasi. Keng o'qish zallari, bepul Wi-Fi va ilmiy resurslar.",
        "type": "library",
        "address": "Navoiy ko'chasi 1",
        "district": "olmazor",
        "latitude": 41.3111,
        "longitude": 69.2798,
        "price": 0,
        "working_hours": "09:00-20:00",
        "wifi_speed": 50,
        "noise_level": "quiet",
        "sockets": True,
        "capacity": 500,
        "available_seats": 200,
        "rating": 4.9,
        "amenities": "Wi-Fi, Rozetka, O'qish zallari, Ilmiy resurslar, Nusxa ko'chirish",
    },
    {
        "name": "Toshkent axborot-resurs markazi",
        "description": "Zamonaviy axborot-resurs markazi. O'qish, tadqiqot va bepul internet.",
        "type": "library",
        "address": "Amir Temur shoh ko'chasi 1",
        "district": "yakkasaroy",
        "latitude": 41.3117,
        "longitude": 69.2785,
        "price": 0,
        "working_hours": "09:00-21:00",
        "wifi_speed": 60,
        "noise_level": "quiet",
        "sockets": True,
        "capacity": 300,
        "available_seats": 120,
        "rating": 4.8,
        "amenities": "Wi-Fi, Rozetka, Kompyuter xonasi, Elektron kutubxona",
    },
    {
        "name": "Fanlar akademiyasi Markaziy ilmiy kutubxonasi",
        "description": "O'zbekiston Fanlar akademiyasining markaziy ilmiy kutubxonasi. Ilmiy adabiyotlar boy to'plami.",
        "type": "library",
        "address": "Yunus Rajabiy ko'chasi 69",
        "district": "yakkasaroy",
        "latitude": 41.3264,
        "longitude": 69.2818,
        "price": 0,
        "working_hours": "09:00-18:00",
        "wifi_speed": 40,
        "noise_level": "quiet",
        "sockets": True,
        "capacity": 250,
        "available_seats": 90,
        "rating": 4.7,
        "amenities": "Wi-Fi, Rozetka, Ilmiy jurnallar, O'qish xonalari",
    },
    {
        "name": "Yunusobod tuman markaziy kutubxonasi",
        "description": "Yunusobod tumani markaziy kutubxonasi. Tinch o'qish muhiti, bepul kirish.",
        "type": "library",
        "address": "Amir Temur shoh ko'chasi 8A",
        "district": "yunusobod",
        "latitude": 41.3652,
        "longitude": 69.2885,
        "price": 0,
        "working_hours": "09:00-19:00",
        "wifi_speed": 35,
        "noise_level": "quiet",
        "sockets": True,
        "capacity": 120,
        "available_seats": 55,
        "rating": 4.5,
        "amenities": "Wi-Fi, Rozetka, Bolalar bo'limi, O'qish zali",
    },
    {
        "name": "Chilonzor tuman markaziy kutubxonasi",
        "description": "Chilonzor tumani markaziy kutubxonasi. Talabalar va o'quvchilar uchun qulay.",
        "type": "library",
        "address": "Katartal ko'chasi 2",
        "district": "chilonzor",
        "latitude": 41.2855,
        "longitude": 69.2045,
        "price": 0,
        "working_hours": "09:00-19:00",
        "wifi_speed": 30,
        "noise_level": "quiet",
        "sockets": True,
        "capacity": 100,
        "available_seats": 45,
        "rating": 4.4,
        "amenities": "Wi-Fi, Rozetka, O'qish zali, Bolalar adabiyoti",
    },
    {
        "name": "Mirzo Ulug'bek tuman markaziy kutubxonasi",
        "description": "Mirzo Ulug'bek tumani markaziy kutubxonasi. Keng o'qish zali va bepul Wi-Fi.",
        "type": "library",
        "address": "Temur Malik ko'chasi 25",
        "district": "mirzo ulug'bek",
        "latitude": 41.3405,
        "longitude": 69.3355,
        "price": 0,
        "working_hours": "09:00-19:00",
        "wifi_speed": 35,
        "noise_level": "quiet",
        "sockets": True,
        "capacity": 110,
        "available_seats": 50,
        "rating": 4.5,
        "amenities": "Wi-Fi, Rozetka, O'qish zali",
    },
    {
        "name": "Yakkasaroy tuman markaziy kutubxonasi",
        "description": "Yakkasaroy tumani markaziy kutubxonasi. Markaziy hududda joylashgan.",
        "type": "library",
        "address": "Shota Rustaveli ko'chasi 71",
        "district": "yakkasaroy",
        "latitude": 41.2925,
        "longitude": 69.2745,
        "price": 0,
        "working_hours": "09:00-19:00",
        "wifi_speed": 30,
        "noise_level": "quiet",
        "sockets": True,
        "capacity": 90,
        "available_seats": 40,
        "rating": 4.3,
        "amenities": "Wi-Fi, Rozetka, O'qish zali",
    },
    {
        "name": "Shayxontohur tuman markaziy kutubxonasi",
        "description": "Shayxontohur tumani markaziy kutubxonasi. Tarixiy markaz yaqinida.",
        "type": "library",
        "address": "Labzak ko'chasi 1",
        "district": "shayxontohur",
        "latitude": 41.3180,
        "longitude": 69.2380,
        "price": 0,
        "working_hours": "09:00-19:00",
        "wifi_speed": 30,
        "noise_level": "quiet",
        "sockets": True,
        "capacity": 80,
        "available_seats": 35,
        "rating": 4.3,
        "amenities": "Wi-Fi, Rozetka, O'qish zali",
    },
    {
        "name": "Olmazor tuman markaziy kutubxonasi",
        "description": "Olmazor tumani markaziy kutubxonasi. Bepul o'qish va internet.",
        "type": "library",
        "address": "Talabalar ko'chasi 10",
        "district": "olmazor",
        "latitude": 41.3520,
        "longitude": 69.2060,
        "price": 0,
        "working_hours": "09:00-19:00",
        "wifi_speed": 30,
        "noise_level": "quiet",
        "sockets": True,
        "capacity": 85,
        "available_seats": 38,
        "rating": 4.2,
        "amenities": "Wi-Fi, Rozetka, O'qish zali",
    },
    {
        "name": "Sergeli tuman markaziy kutubxonasi",
        "description": "Sergeli tumani markaziy kutubxonasi. Janubiy Toshkent hududida.",
        "type": "library",
        "address": "Sergeli-7 mahallasi",
        "district": "sergeli",
        "latitude": 41.2280,
        "longitude": 69.2300,
        "price": 0,
        "working_hours": "09:00-19:00",
        "wifi_speed": 25,
        "noise_level": "quiet",
        "sockets": True,
        "capacity": 70,
        "available_seats": 30,
        "rating": 4.1,
        "amenities": "Wi-Fi, Rozetka, O'qish zali",
    },
    {
        "name": "TDPU ilmiy kutubxonasi",
        "description": "Toshkent davlat pedagogika universiteti ilmiy kutubxonasi. Pedagogik adabiyotlar.",
        "type": "library",
        "address": "Chilonzor ko'chasi 27",
        "district": "chilonzor",
        "latitude": 41.3380,
        "longitude": 69.2410,
        "price": 0,
        "working_hours": "08:30-17:30",
        "wifi_speed": 45,
        "noise_level": "quiet",
        "sockets": True,
        "capacity": 200,
        "available_seats": 80,
        "rating": 4.6,
        "amenities": "Wi-Fi, Rozetka, Ilmiy adabiyotlar, O'qish zali",
    },
    {
        "name": "Toshkent davlat iqtisodiyot universiteti kutubxonasi",
        "description": "TSUE ilmiy kutubxonasi. Iqtisodiyot va biznes adabiyotlari.",
        "type": "library",
        "address": "Islom Karimov ko'chasi 49",
        "district": "yunusobod",
        "latitude": 41.3270,
        "longitude": 69.2890,
        "price": 0,
        "working_hours": "08:30-18:00",
        "wifi_speed": 50,
        "noise_level": "quiet",
        "sockets": True,
        "capacity": 180,
        "available_seats": 70,
        "rating": 4.5,
        "amenities": "Wi-Fi, Rozetka, Ilmiy bazalar, O'qish zali",
    },
    {
        "name": "O'zbekiston davlat jahon tillari universiteti kutubxonasi",
        "description": "UzDJTU kutubxonasi. Chet tillari adabiyotlari va o'qish zonalari.",
        "type": "library",
        "address": "Uzbekistan ovozi ko'chasi 103",
        "district": "yakkasaroy",
        "latitude": 41.2990,
        "longitude": 69.2680,
        "price": 0,
        "working_hours": "08:30-17:30",
        "wifi_speed": 40,
        "noise_level": "quiet",
        "sockets": True,
        "capacity": 150,
        "available_seats": 60,
        "rating": 4.4,
        "amenities": "Wi-Fi, Rozetka, Chet til adabiyotlari",
    },
    {
        "name": "Toshkent davlat yuridik universiteti kutubxonasi",
        "description": "TDYU ilmiy kutubxonasi. Huquq va yurisprudensiya adabiyotlari.",
        "type": "library",
        "address": "Sayilgoh ko'chasi 35",
        "district": "yakkasaroy",
        "latitude": 41.3040,
        "longitude": 69.2710,
        "price": 0,
        "working_hours": "08:30-17:30",
        "wifi_speed": 40,
        "noise_level": "quiet",
        "sockets": True,
        "capacity": 130,
        "available_seats": 55,
        "rating": 4.4,
        "amenities": "Wi-Fi, Rozetka, Huquq adabiyotlari",
    },
]
